In [2]:
import numpy as np

In [37]:
mat1D = np.array([2,3,4,5,6,7,8,9,10,11])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [87]:
print(mat1D[0])

2


In [89]:
print (mat1D + 5)

[ 7  8  9 10 11 12 13 14 15 16]


In [41]:
print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [55]:
print(mat2D[2][2])

9


In [59]:
print(mat2D * 5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [65]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [83]:
print(mat1D.size)
print(mat2D.size)

10
9


In [134]:
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4,),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size=6)

In [136]:
print (mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
print (mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [140]:
print (mFull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [142]:
print (mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [146]:
print (mRandomFloat)

[[0.55338544 0.6762306  0.34521466 0.57808456 0.93726014]
 [0.43790256 0.44607129 0.75964893 0.41245506 0.69564836]
 [0.71508303 0.37167076 0.33432933 0.18103114 0.58808278]
 [0.39587003 0.44827482 0.76941102 0.33626713 0.3409481 ]
 [0.92326184 0.55620596 0.07945883 0.1874114  0.30639026]]


In [148]:
print (mRandomInt)

[64 46 18 43 75 99]


In [172]:
x = np.array([2,6,9])
y = np.array([1,3,5])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)
print (f"Hasil dari dot Product :{dotProduct}")
print (f"Hasil penjumlahan matrix :{addMatrix}")
print (f"Nilai minimum dari {x}:{minValue}")
print (f"Nilai maximal dari {y}:{maxValue}")
print (f"Rata-rata Nilai dari {y}:{meanValue}")
print (f"Nilai median dari {y}:{medianValue}")
print (f"Nilai Deviasi dari {y}:{stdValue}")

Hasil dari dot Product :65
Hasil penjumlahan matrix :[ 3  9 14]
Nilai minimum dari [2 6 9]:2
Nilai maximal dari [1 3 5]:5
Rata-rata Nilai dari [1 3 5]:3.0
Nilai median dari [1 3 5]:3.0
Nilai Deviasi dari [1 3 5]:1.632993161855452


In [178]:
myArray = np.array([[1,2,3],[4,5,6]])

reshape = myArray.reshape(2,3)
flatten = myArray.flatten

print(reshape)
print(flatten)

[[1 2 3]
 [4 5 6]]
<built-in method flatten of numpy.ndarray object at 0x13f945f50>


In [186]:
#filetering
nilaiSiswa = np.array([80,90,60,65,75,93])
lulus = nilaiSiswa[nilaiSiswa > 85]
jumlah = lulus.size
print (lulus)
print (f"Jumlah siswa yang lulus:{jumlah}")

[90 93]
Jumlah siswa yang lulus:2
